import streamlit as st

# Set the page title and icon
st.set_page_config(page_title='DCGAN AI Model', page_icon='🖼️')

# Define the content of the page


def main():
    st.markdown('<h1 style="text-align:center;">Deep Convolutional Generative Adversarial Network (DCGAN)</h1>',
                unsafe_allow_html=True)

    st.markdown('## 🤔 What is a DCGAN?')
    st.write('A DCGAN is a type of deep generative model that is used to generate new realistic images from a training dataset. It consists of two main parts: the generator and the discriminator.')

    st.markdown('## 🎯 What can a DCGAN be used for?')
    st.write('DCGANs are used to generate realistic images in domains such as anime image generation, visual art creation, and texture synthesis. They also allow for exploring and understanding the hidden features of the training data.')

    st.markdown('## 🧐 How does a DCGAN work?')
    st.write('The generator takes a random noise vector as input and generates an image from that noise. The discriminator takes an image as input and tries to determine whether it comes from the generator (fake) or the real training data (real). Both models are trained adversarially, meaning the generator seeks to deceive the discriminator while the discriminator tries to distinguish real images from fake images generated by the generator.')

    st.markdown('## 👩‍💻 Ready to try it out?')
    st.write('We have included a DCGAN model that you can use to generate images from a training dataset.')


# Call the main function to run the application
main()
